### ISSUE TITLE
Footers are not consistant across all web pages

### ISSUE THREAD

**Issue by froreWolf** [ASHLANDACMCLUB/ashlandacmclub.github.io#19]
The footers of most pages are different depending on the page they should be synchronized so that they have the same look to them. That would look more professional

**Comment by jimender2** [comment]
Do you have one that is perfect or good enough?

**Comment by froreWolf** [comment]
I would say the one on index.html some of the other ones have other links or are missing hte bar thingy that the main page does

**Comment by froreWolf** [comment]
Either way I'm planning on doing most of these tonight, that way y'all can look at them tomarrow
